### PR TITLE
Add support for Django 3.0

### PR DESCRIPTION
**Pull request by noamkush**

### CODE REVIEW

**Comment by adamchainz** [comment]
I’m not intending to maintain this very much. That said I’d be happy to merge a Django 3 compatibility PR but not a removal of Python 2.7. Please revert all the Python 2.7 removal changes :)

**Comment by noamkush** [comment]
I reverted the parts dropping Python 2.7. This means `six` must be a direct dependency.

**Comment by robertpro** [comment]
I can confirm this commit is working on Django 3, no other issues.

Please merge.

**Comment by adamchainz** [comment]
Released in version 1.4.0: https://pypi.org/project/django-jsonfield/1.4.0/

Thanks @noamkush for the patch and @robertpro for confirming it works.

I haven't run the tests because they're hard to get going so I'm trusting your verification :)

**Pull request merged**
